### ISSUE TITLE
Cannot open '/dev/video0' 

### ISSUE THREAD

**Issue by jenny-1996** [baresip/baresip#987]
Sorry, I have some questions about the video stream of baresip. Can you help me?

After I set the video configuration in .baresip/config, the video stream still didn't work during the call. (But the audio part can work normally!)
This is my setting about video:
```
# Video
video_source            v4l2,/dev/video0
video_display           x11,nil
video_size              352x288
video_bitrate           500000
video_fps               25.00
video_fullscreen        no
videnc_format           yuv420p

# AVT - Audio/Video Transport
rtp_tos                 184
#rtp_ports              10000-20000
#rtp_bandwidth          512-1024 # [kbit/s]
rtcp_mux                no
jitter_buffer_delay     5-10            # frames
rtp_stats               yes
#rtp_timeout            60

==============================
# Video codec Modules (in order)
#module                 avcodec.so
module                  vp8.so
#module                 vp9.so

# Video filter Modules (in encoding order)
#module                 selfview.so
#module                 snapshot.so
#module                 swscale.so
#module                 vidinfo.so

# Video source modules
module                  v4l2.so
#module                 v4l2_codec.so
#module                 x11grab.so
#module                 cairo.so
#module                 vidbridge.so

# Video display modules
#module                 directfb.so
module                  x11.so
module                  sdl.so
#module                 fakevideo.so
```

And when I run "baresip -v": 
```
yc@yc-VirtualBox:~/Downloads/baresip-master$ baresip -v
baresip v0.6.6 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Local network address:  IPv4=enp0s3|192.168.50.150 
ui: stdio
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: VP8
vidsrc: v4l2
vidisp: x11
vidisp: sdl
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID 452fb474-0637-f9f2-36e8-095ca3f8a504 from file /home/yc/.baresip/uuid
Populated 1 account
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 2 audio codecs
Populated 0 audio filters
Populated 1 video codec
Populated 0 video filters
baresip is ready.
ua: incoming OPTIONS message from sip:asterisk@192.168.50.235 (192.168.50.235:5060)
ua: using best effort AF: af=AF_INET
call: alloc with params laddr=192.168.50.150, af=AF_INET, use_rtp=0
call: use_video=1
video: stopping video source ..
audio: destroyed (started=0)
alice@192.168.50.150: {0/UDP/v4} 200 OK (Asterisk PBX 15.7.4) [1 binding]
All 1 useragent registered successfully! (11 ms)
```

And when I run "\vidloop", It show that it cannot find '/dev/video0':
```
/vidloop
Enable video-loop on v4l2,/dev/video0: 352 x 288
vidloop: open video display (x11.nil)
vidloop: v4l2,/dev/video0: open video source: 352 x 288 at 25.00 fps
v4l2: open /dev/video0: No such file or directory
v4l2: stopping video source..
vidloop: vidsrc '/dev/video0' failed: No such file or directory
```

During the call, the video stream seems to zero data transmit:
```
ua: using best effort AF: af=AF_INET0 (bit/s) efps=0.0/0.0    
ua: using best effort AF: af=AF_INET0 (bit/s) efps=0.0/0.0    
[0:02:26] audio=64831/64000 video=0/0 (bit/s) efps=0.0/0.0
...
ua: using best effort AF: af=AF_INET0 (bit/s) efps=0.0/0.0    
call: terminate call '2273624b2fb3adae3ac7720b154a9614@192.168.50.235:5060' with sip:7002@192.168.50.235
sip:alice-0x1f31620@192.168.50.150:48426: Call with sip:7002@192.168.50.235 terminated (duration: 2 mins 42 secs)

audio           Transmit:     Receive:
packets:           8113         8079
avg. bitrate:      63.8         63.7  (kbit/s)
errors:               0            0
pkt.report:        7992            0
lost:                 0            0
jitter:            16.0          0.0  (ms)
```

How can I fix it? Is that the problem of my camera device ? or is there something wrong with my config file?

Thank you very much!!

**Comment by juha-h** [comment]
Are you sure this is a baresip related issue?  Try, for example. with
Linux app 'cheese' if your webcam is working.

**Comment by jenny-1996** [comment]
Thank you! My webcam can work. 
But I encounter another problem...
I want to dial a video call, and I select the following video modules:
```
video codec module:   avcodec.so
video source module:  v4l2_codec.so
video display module: x11.so
```
When I dial, the console show these messages: 
```
baresip v1.0.0 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Local network address:  IPv4=enp0s3|172.17.180.134 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
v4l2_codec inited
vidcodec: H264
vidsrc: v4l2_codec
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 6 video codecs
Populated 0 video filters
baresip is ready.
ua: using best effort AF: af=AF_INET
bob@172.17.180.134: {0/UDP/v4} 200 OK (Asterisk PBX 16.10.0) [1 binding]
All 1 useragent registered successfully! (2 ms)
                            7001

ua: using best effort AF: af=AF_INET
call: connecting to 'sip:7001@172.17.180.134'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
stream: update 'audio'
stream: update 'video'
audio: Set audio decoder: PCMA 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMA 8000Hz 1ch
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> PCMA
audio rx pipeline:        alsa <--- PCMA
Set video encoder: H263  (500000 bit/s, 25.00 fps)
h263: SQCIF: MPI out of range 0
h263: QCIF: MPI out of range 0
h263: CIF16: MPI out of range 0
h263: unknown param 'VGA'
h263: unknown param 'F'
h263: unknown param 'I'
h263: unknown param 'J'
h263: unknown param 'T'
h263: unknown param 'K'
h263: unknown param 'N'
h263: unknown param 'BPP'
h263: unknown param 'HRD'
v4l2_codec: Driver Caps:
  Driver:        "uvcvideo"
  Card:          "VirtualBox Webcam - HD Pro Webc"
  Bus:           "usb-0000:00:06.0-2"
  Version:       4.0
  Capabilities:  0x84200001
  Formats:
     MJPG: C  'Motion-JPEG'

v4l2_codec: Doesn't support H264.
v4l2_codec: encoder stats (keyframes:0, deltaframes:0)
video: could not set source to [352 x 288] No such device
Set video decoder: H263 
bob@172.17.180.134: Call established: sip:7001@172.17.180.134
```
It still cannot view the video. Is my setting in config file wrong?

Thank you very much.
